### ISSUE TITLE
Encoding namespace clashes with 1.9

### ISSUE THREAD

**Issue by oggy** [now/character-encodings#1]
Ruby 1.9 defines an Encoding constant. Furthermore, some gems that need to detect string encodings in 1.9 check for the presence of an Encoding constant to perform encoding handling. These libraries cannot be used with character-encodings.

There are two possible solutions to this:
- character-encodings should not use the Encoding namespace.
- the other libraries should not use "defined?(::Encoding)" to check for encoding support.

I feel the former is the lesser of the two evils.

Thoughts?

Happy to provide a patch if necessary.

**Comment by now** [comment]
Note that this library is mainly for 1.8.*.

How do we solve this?  I mean, I don’t feel like changing the namespace, but I suppose that’s the only real solution.

**Comment by oggy** [comment]
Hi Nikolai,

We're using this with 1.8 too. The problem is we're also using libraries that assume the presence of ::Encoding means we have 1.9-compliant String encoding semantics. As faulty as that assumption may be, it's probably not great to use a namespace that collides with a now-standard Ruby library, so I agree it is the better solution.

If the transition is a concern, you could use Object.const_missing to print a deprecation warning and alias the new name to ::Encoding. Combined with a major version bump, I think that should go down fine.

Let me know if you'd like a patch.

George

**Comment by now** [comment]
As you haven’t responded per mail, I figured I’d propose my change here.  I was thinking of renaming this whole library to something more suiting.  This is perhaps a gratuitous change, but names are important.  What do you think of such a change?  Would it be easy for you to adjust to such a change?  I was thinking of going with something simple like Runicode or U.  I guess the 'encoding/character/utf-8' include would remain with a deprecation warning and everything would be moved into a new namespace (since the namespace hasn’t really been part of the public API anyway) and one would in the future simply require 'runicode' or 'u'.

What do you think?

M

**Comment by oggy** [comment]
Hi Nikolai,

Sorry I forget to get back to you. Changing the name of the gem is fine for me. In fact, I personally like adhering to the dominant convention, where a gem called "runicode" would have a toplevel namespace "Runicode" which is required as "runicode". Practically speaking, this has the advantage of playing better with tools like Bundler and ActiveSupport autoloading.

I prefer "Runicode" to "U". Much more descriptive; if someone wants, they can always alias it.

Thanks!
George
